
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod 
metadata:
  name: mysql
  labels:
    app: mysql 
spec:
  containers:
    - image: mysql:5.7
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - name: hostvol
          mountPath: /var/lib/mysql
      readinessProbe:
        exec:
          command: ["mysql", "-h", "127.0.0.1","-proot", "-e", "SELECT 1"]
        initialDelaySeconds: 10
        periodSeconds: 3
        timeoutSeconds: 1
      livenessProbe:
        exec:
          command: ["mysqladmin","-proot","ping"]
        initialDelaySeconds: 10 
        periodSeconds: 3
        timeoutSeconds: 1 
  volumes:
    - name: hostvol
      persistentVolumeClaim:
        claimName: mysql-pvc