apiVersion: v1
kind: Pod 
metadata:
  name: mysql
  labels:
    app: mysql 
spec:
  containers:
    - image: mysql:5.7
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - name: hostvol
          mountPath: /var/lib/mysql
      readinessProbe:
        tcpSocket:
          port: 3306
      livenessProbe:
        exec:
          command: ["mysqladmin","-proot","ping"]
        initialDelaySeconds: 10 
        periodSeconds: 3
        timeoutSeconds: 1 
  volumes:
    - name: hostvol
      hostPath:
        path: /dbdata
        type: DirectoryOrCreate
